# Generated by Django 5.0.7 on 2024-10-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0013_remove_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=2),
        ),
    ]
